### ISSUE TITLE
Use the new LetsEncrypt stuff for https

### ISSUE THREAD

**Issue by todb-r7** [AustinHackers/austinhackers.github.io#100]
We should redirect to an HTTPS version of the site with GitHub's new LetsEncrypt automation.

Feel free to assign this back to me (apparently this account of mine doesn't have commit rights here, also I'll fix that)

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by mauvehed** [comment]
This is resolved by moving to cloudflare for a front-end. HSTS, TLS v1.2+ required, HTTP redirects to HTTPS.
