### ISSUE TITLE
Fix mobile rendering

### ISSUE THREAD

**Issue by todb** [AustinHackers/austinhackers.github.io#159]
This is certainly dependent on #148

View on Safari on iOS:

![image](https://github.com/AustinHackers/austinhackers.github.io/assets/24144/e1697b7d-1a20-437f-aafd-3227bd7582f4)

**Comment by mauvehed** [comment]
What in the hell did you do to my (not so) beautiful website?

**Comment by todb** [comment]
I would say i borked it, but it was already borked with the broken image.

I'm sure it's fixable with some css-fu.
