### ISSUE TITLE
Templatize more of the meeting notes

### ISSUE THREAD

**Issue by todb** [AustinHackers/austinhackers.github.io#44]
The copy-pasta about Tramps should be in a layout or something.

Incidentally, might do a whole overhaul using [Middleman](http://middlemanapp.com/).

**Comment by mauvehed** [comment]
So if we change more of the meeting layout to a template we have to revise some of the wording. Look at the current file and you can see we include the meeting number and other data from the config section. As it's only used once it Kay not be worth doing that way. I'm still open to full rewrites.
